apiVersion: v1
kind: Service
metadata:
  name: openclaw-gateway
spec:
  type: NodePort
  selector:
    sandbox: openclaw-template-sandbox
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      nodePort: 30789
